[package]
name = "cch23-variasuit32"
version = "1.0.0"
edition = "2021"

[dependencies]
base64 = "0.21.5"
image = { version = "0.24.7", features = ["png"] }
rocket = { version = "0.5.0", features = ["json"] }
rustemon = "3.2.1"
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
