[package]
name = "cch23-variasuit32"
version = "1.0.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
